# Generated by Django 2.2.5 on 2019-10-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relator', models.CharField(choices=[('Relator 1', 'Relator 1'), ('Relator 2', 'Relator 2'), ('Relator 3', 'Relator 3')], max_length=50)),
                ('orientador', models.CharField(choices=[('Orientador 1', 'Orientaor 1'), ('Orientador 2', 'Orientador 2'), ('Orientador 3', 'Orientador 3')], max_length=50)),
                ('programa', models.CharField(choices=[('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós Doutorado', 'Pós Doutorado')], max_length=50)),
                ('relatorio', models.FileField(upload_to='uploads/relatorios/%Y/%m/%d/')),
                ('encaminhamento', models.FileField(upload_to='uploads/encamnhamentos/%Y/%m/%d/')),
            ],
        ),
    ]
