# Generated by Django 2.2.6 on 2019-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='encaminhamento',
            field=models.FileField(upload_to='encamnhamentos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='relatorio',
            field=models.FileField(upload_to='relatorios/%Y/%m/%d/'),
        ),
    ]
