# Generated by Django 2.2.6 on 2019-11-17 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20191117_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecerorientadormestrado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
    ]
