# Generated by Django 2.2.6 on 2019-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_parecerorientadormestrado_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecerorientadormestrado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
