# Generated by Django 2.2.6 on 2019-11-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_parecerorientadormestrado_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
        ),
    ]
