# Generated by Django 2.2.6 on 2019-11-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20191117_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='semestre',
            field=models.CharField(choices=[('Primeiro Semestre', 'Primeiro Semestre'), ('Segundo Semestre', 'Segundo Semestre'), ('Terceiro Semestre', 'Terceiro Semestre')], default='Primeiro Semestre', max_length=50),
            preserve_default=False,
        ),
    ]
