# Generated by Django 2.2.6 on 2019-11-24 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_report_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='encaminhamento',
        ),
        migrations.RemoveField(
            model_name='report',
            name='orientador',
        ),
        migrations.RemoveField(
            model_name='report',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='report',
            name='relator',
        ),
        migrations.RemoveField(
            model_name='report',
            name='relatorio',
        ),
        migrations.RemoveField(
            model_name='report',
            name='semestre',
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('Primeiro Semestre', 'Primeiro Semestre'), ('Segundo Semestre', 'Segundo Semestre'), ('Terceiro Semestre', 'Terceiro Semestre')], max_length=50)),
                ('relator', models.CharField(choices=[('Relator 1', 'Relator 1'), ('Relator 2', 'Relator 2'), ('Relator 3', 'Relator 3')], max_length=50)),
                ('orientador', models.CharField(choices=[('Orientador 1', 'Orientaor 1'), ('Orientador 2', 'Orientador 2'), ('Orientador 3', 'Orientador 3')], max_length=50)),
                ('programa', models.CharField(choices=[('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós Doutorado', 'Pós Doutorado')], max_length=50)),
                ('relatorio', models.FileField(upload_to='relatorios/%Y/%m/%d/')),
                ('encaminhamento', models.FileField(upload_to='encamnhamentos/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
    ]
