# Generated by Django 3.0.1 on 2020-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20191124_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s2_abordagem',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Abordagem do problema a ser investigado'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s2_desempenho',
            field=models.TextField(blank=True, max_length=2048, verbose_name='desempenho das disciplinas'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s2_metodologia',
            field=models.TextField(blank=True, max_length=2048, verbose_name='texto sobre a metodologia de trabalho'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s2_outras_atividades',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s3_outras_atividades',
            field=models.TextField(blank=True, max_length=2048, verbose_name='outras atividades'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s3_perspectivas',
            field=models.TextField(blank=True, max_length=2048, verbose_name='perspectivas para a conclusão da dissertação'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s3_resultados',
            field=models.TextField(blank=True, max_length=2048, verbose_name='resultados'),
        ),
        migrations.AlterField(
            model_name='parecerorientadormestrado',
            name='s3_resumo',
            field=models.TextField(blank=True, max_length=2048, verbose_name='resumo expandido'),
        ),
    ]
