# Generated by Django 3.0.1 on 2020-02-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20200121_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestre',
            options={'permissions': [('change_semestre_relator', 'Can change semestre relator')]},
        ),
    ]
